openapi: 3.2.0
info:
  description: You're looking at the current **stable** documentation of the OpenProject APIv3.
  title: OpenProject API V3 (Stable) Programs API
  version: '3'
servers:
- url: https://qa.openproject-edge.com
  description: Edge QA instance
- url: https://qa.openproject-stage.com
  description: Staging instance
- url: https://community.openproject.org
  description: Community instance
security:
- BasicAuth: []
tags:
- description: 'Programs are one of the types of workspaces in OpenProject structuring the information

    (e.g.'
  name: Programs
paths:
  /api/v3/programs:
    get:
      summary: List programs
      operationId: list_programs
      tags:
      - Programs
      description: Returns a collection of programs. The collection can be filtered via query parameters similar to how work packages are filtered. In addition to the provided filter, the result set is always limited to only contain programs the client is allowed to see.
      parameters:
      - name: filters
        schema:
          type: string
        in: query
        required: false
        description: 'JSON specifying filter conditions.

          Accepts the same format as returned by the [queries](https://www.openproject.org/docs/api/endpoints/queries/) endpoint.

          Currently supported filters are:


          + active: based on the active property of the program

          + ancestor: filters programs by their ancestor. A program is not considered to be its own ancestor.

          + available_project_attributes: filters programs based on the activated project attributes.

          + created_at: based on the time the program was created

          + favorited: based on the favorited property of the program

          + id: based on programs'' id.

          + latest_activity_at: based on the time the last activity was registered on a program.

          + name_and_identifier: based on both the name and the identifier.

          + parent_id: filters programs by their parent.

          + principal: based on members of the program.

          + project_phase_any: based on the project phases active in a program.

          + project_status_code: based on status code of the program

          + storage_id: filters programs by linked storages

          + storage_url: filters programs by linked storages identified by the host url

          + type_id: based on the types active in a program.

          + user_action: based on the actions the current user has in the program.

          + visible: based on the visibility for the user (id) provided as the filter value. This filter is useful for admins to identify the programs visible to a user.


          There might also be additional filters based on the custom fields that have been configured.


          Each defined lifecycle step will also define a filter in this list endpoint. Given that the elements are not

          static but rather dynamically created on each OpenProject instance, a list cannot be provided. Those filters follow the schema:

          + project_start_gate_[id]: a filter on a project phase''s start gate active in a program. The id is the id of the phase the gate belongs to.

          + project_finish_gate_[id]: a filter on a project phase''s finish gate active in a program. The id is the id of the phase the gate belongs to.

          + project_phase_[id]: a filter on a project phase active in a program. The id is the id of the phase queried for.'
        example: '[{ "ancestor": { "operator": "=", "values": ["1"] }" }]'
      - name: sortBy
        schema:
          type: string
        in: query
        required: false
        description: 'JSON specifying sort criteria.

          Currently supported orders are:


          + id

          + name

          + typeahead (sorting by hierarchy and name)

          + created_at

          + public

          + latest_activity_at

          + required_disk_space


          There might also be additional orders based on the custom fields that have been configured.'
        example: '[["id", "asc"]]'
      - name: select
        schema:
          type: string
        in: query
        required: false
        description: Comma separated list of properties to include.
        example: total,elements/identifier,elements/name
      responses:
        '200':
          description: OK
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/ProgramCollectionModel'
              examples:
                simple program collection:
                  $ref: '#/components/examples/ProgramCollection'
        '400':
          description: Returned if the client sends invalid request parameters e.g. filters
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                _type: Error
                errorIdentifier: urn:openproject-org:api:v3:errors:InvalidQuery
                message: Filters Invalid filter does not exist.
  /api/v3/programs/{id}:
    get:
      parameters:
      - description: Program id
        example: 1
        in: path
        name: id
        required: true
        schema:
          type: integer
      responses:
        '200':
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/ProgramModel'
          description: OK
          headers: {}
        '404':
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                response:
                  value:
                    _type: Error
                    errorIdentifier: urn:openproject-org:api:v3:errors:NotFound
                    message: The requested resource could not be found.
          description: 'Returned if the program does not exist or the client does not have sufficient permissions

            to see it.


            **Required permission:** any permission in the program


            *Note: A client without sufficient permissions shall not be able to test for the existence of a program.

            That''s why a 404 is returned here, even if a 403 might be more appropriate.*'
          headers: {}
      tags:
      - Programs
      description: ''
      operationId: View_program
      summary: View program
    patch:
      parameters:
      - description: Program id
        example: 1
        in: path
        name: id
        required: true
        schema:
          type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProgramModel'
            examples:
              with custom fields:
                $ref: '#/components/examples/ProgramBody'
      responses:
        '200':
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/ProgramModel'
              examples:
                with custom fields:
                  $ref: '#/components/examples/Program'
          description: OK
          headers: {}
        '400':
          $ref: '#/components/responses/InvalidRequestBody'
        '403':
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                response:
                  value:
                    _type: Error
                    errorIdentifier: urn:openproject-org:api:v3:errors:MissingPermission
                    message: You are not authorized to access this resource.
          description: 'Returned if the client does not have sufficient permissions.


            **Required permission:** edit project for the program to be altered'
          headers: {}
        '404':
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                response:
                  value:
                    _type: Error
                    errorIdentifier: urn:openproject-org:api:v3:errors:NotFound
                    message: The requested resource could not be found.
          description: 'Returned if the program does not exist or the client does not have sufficient permissions

            to see it.


            **Required permission:** view project


            *Note: A client without sufficient permissions shall not be able to test for the existence of

            a version. That''s why a 404 is returned here, even if a 403 might be more appropriate.*'
          headers: {}
        '406':
          $ref: '#/components/responses/MissingContentType'
        '415':
          $ref: '#/components/responses/UnsupportedMediaType'
        '422':
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                response:
                  value:
                    _embedded:
                      details:
                        attribute: name
                    _type: Error
                    errorIdentifier: urn:openproject-org:api:v3:errors:PropertyConstraintViolation
                    message: Name can't be blank.
          description: 'Returned if:


            * a constraint for a property was violated (`PropertyConstraintViolation`)'
          headers: {}
      tags:
      - Programs
      description: Updates the given program by applying the attributes provided in the body.
      operationId: Update_Program
      summary: Update Program
    delete:
      parameters:
      - description: Program id
        example: 1
        in: path
        name: id
        required: true
        schema:
          type: integer
      responses:
        '204':
          description: 'Returned if the program was successfully deleted. There is currently no endpoint to query for the actual deletion status.

            Such an endpoint _might_ be added in the future.'
          headers: {}
        '403':
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                response:
                  value:
                    _type: Error
                    errorIdentifier: urn:openproject-org:api:v3:errors:MissingPermission
                    message: You are not authorized to access this resource.
          description: 'Returned if the client does not have sufficient permissions.


            **Required permission:** admin'
          headers: {}
        '404':
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                response:
                  value:
                    _type: Error
                    errorIdentifier: urn:openproject-org:api:v3:errors:NotFound
                    message: The requested resource could not be found.
          description: 'Returned if the program does not exist or the client does not have sufficient permissions

            to see it.


            **Required permission:** any permission in the program


            *Note: A client without sufficient permissions shall not be able to test for the existence of

            a version. That''s why a 404 is returned here, even if a 403 might be more appropriate.*'
          headers: {}
        '406':
          $ref: '#/components/responses/MissingContentType'
        '415':
          $ref: '#/components/responses/UnsupportedMediaType'
        '422':
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                response:
                  value:
                    _embedded:
                      details:
                        attribute: base
                    _type: Error
                    errorIdentifier: urn:openproject-org:api:v3:errors:PropertyConstraintViolation
                    message: Work packages in non descendant projects reference versions of the program or its descendants.
          description: 'Returned if the program cannot be deleted. This can happen when there are still references to the program in other workspaces

            that need to be severed at first.'
          headers: {}
      tags:
      - Programs
      description: 'Deletes the program permanently. As this is a lengthy process, the actual deletion is carried out asynchronously.

        So the program might exist well after the request has returned successfully. To prevent unwanted changes to

        the program scheduled for deletion, it is archived at once.'
      operationId: Delete_Program
      summary: Delete Program
  /api/v3/programs/{id}/form:
    post:
      parameters:
      - description: Program id
        example: 1
        in: path
        name: id
        required: true
        schema:
          type: integer
      requestBody:
        content:
          application/json:
            schema:
              type: object
            examples:
              with custom fields:
                $ref: '#/components/examples/ProgramBody'
              empty:
                description: Empty request to get the form initially in order to start the guided update of a program
                value: {}
      responses:
        '200':
          description: OK
          headers: {}
        '400':
          $ref: '#/components/responses/InvalidRequestBody'
        '403':
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                response:
                  value:
                    _type: Error
                    errorIdentifier: urn:openproject-org:api:v3:errors:MissingPermission
                    message: You are not authorized to access this resource.
          description: 'Returned if the client does not have sufficient permissions.


            **Required permission:** edit workspace in the program'
          headers: {}
        '406':
          $ref: '#/components/responses/MissingContentType'
        '415':
          $ref: '#/components/responses/UnsupportedMediaType'
      tags:
      - Programs
      description: ''
      operationId: Program_update_form
      summary: Program update form
components:
  schemas:
    CustomCommentProperties:
      type: object
      patternProperties:
        ^customComment\d+$:
          type:
          - 'null'
          - string
          description: 'A plain-text comment associated with a project custom field that has comments enabled.


            The property is only present when the corresponding `customField{N}` has `has_comment` set to `true`.'
    CollectionLinks:
      type: object
      required:
      - self
      properties:
        self:
          allOf:
          - $ref: '#/components/schemas/Link'
          - description: 'This collection resource.


              **Resource**: Collection'
    Link:
      type: object
      required:
      - href
      properties:
        href:
          type:
          - string
          - 'null'
          description: URL to the referenced resource (might be relative)
        title:
          type: string
          description: Representative label for the resource
        templated:
          type: boolean
          default: false
          description: If true the href contains parts that need to be replaced by the client
        method:
          type: string
          default: GET
          description: The HTTP verb to use when requesting the resource
        payload:
          type: object
          description: The payload to send in the request to achieve the desired result
        identifier:
          type: string
          description: An optional unique identifier to the link object
        type:
          type: string
          description: The MIME-Type of the returned resource.
      example:
        href: /api/v3/work_packages
        method: POST
    CollectionModel:
      type: object
      required:
      - _type
      - total
      - count
      - _links
      properties:
        _type:
          type: string
          enum:
          - Collection
        total:
          type: integer
          description: The total amount of elements available in the collection.
          minimum: 0
        count:
          type: integer
          description: Actual amount of elements in this response.
          minimum: 0
        _links:
          $ref: '#/components/schemas/CollectionLinks'
    OffsetPaginatedCollectionLinks:
      allOf:
      - $ref: '#/components/schemas/CollectionLinks'
      - type: object
        required:
        - jumpTo
        - changeSize
        properties:
          jumpTo:
            allOf:
            - $ref: '#/components/schemas/Link'
            - description: A templated link to jump to a given offset.
          changeSize:
            allOf:
            - $ref: '#/components/schemas/Link'
            - description: A templated link to change the current page size.
          previousByOffset:
            allOf:
            - $ref: '#/components/schemas/Link'
            - description: 'A link to the previous page of the collection.


                # Conditions

                - The collection is not on the first page.'
          nextByOffset:
            allOf:
            - $ref: '#/components/schemas/Link'
            - description: 'A link to the next page of the collection.


                # Conditions

                - The collection is not on the last page.'
    Formattable:
      type: object
      required:
      - format
      properties:
        format:
          type: string
          enum:
          - plain
          - markdown
          - custom
          readOnly: true
          description: Indicates the formatting language of the raw text
          example: markdown
        raw:
          type: string
          description: The raw text, as entered by the user
          example: I **am** formatted!
        html:
          type: string
          readOnly: true
          description: The text converted to HTML according to the format
          example: I <strong>am</strong> formatted!
      example:
        format: markdown
        raw: I am formatted!
        html: I am formatted!
    OffsetPaginatedCollectionModel:
      allOf:
      - $ref: '#/components/schemas/CollectionModel'
      - type: object
        required:
        - pageSize
        - offset
        - _links
        properties:
          pageSize:
            type: integer
            description: 'The amount of elements per page. If not set by the request this value defaults to the server''s system

              settings.'
            minimum: 0
          offset:
            type: integer
            description: The page offset indicating on which page the element collection starts.
            minimum: 0
          _links:
            $ref: '#/components/schemas/OffsetPaginatedCollectionLinks'
    ProgramCollectionModel:
      allOf:
      - $ref: '#/components/schemas/OffsetPaginatedCollectionModel'
      - type: object
        required:
        - _links
        - _embedded
        properties:
          _links:
            allOf:
            - $ref: '#/components/schemas/OffsetPaginatedCollectionLinks'
            - type: object
              properties:
                representations:
                  type: array
                  items:
                    allOf:
                    - $ref: '#/components/schemas/Link'
                    - description: A program collection representation in a specific file format.
          _embedded:
            type: object
            required:
            - elements
            properties:
              elements:
                type: array
                items:
                  $ref: '#/components/schemas/ProgramModel'
    ProgramModel:
      allOf:
      - $ref: '#/components/schemas/CustomFieldProperties'
      - $ref: '#/components/schemas/CustomCommentProperties'
      - type: object
        properties:
          _type:
            type: string
            enum:
            - Program
          id:
            type: integer
            description: Programs' id
            minimum: 1
          identifier:
            type: string
          name:
            type: string
          active:
            type: boolean
            description: Indicates whether the program is currently active or already archived
          favorited:
            type: boolean
            description: Indicates whether the program is favorited by the current user
          statusExplanation:
            allOf:
            - $ref: '#/components/schemas/Formattable'
            - description: A text detailing and explaining why the program has the reported status
          public:
            type: boolean
            description: Indicates whether the program is accessible for everybody
          description:
            $ref: '#/components/schemas/Formattable'
          createdAt:
            type: string
            format: date-time
            description: Time of creation. Can be writable by admins with the `apiv3_write_readonly_attributes` setting enabled.
          updatedAt:
            type: string
            format: date-time
            description: Time of the most recent change to the program
          _links:
            type: object
            required:
            - self
            - categories
            properties:
              update:
                allOf:
                - $ref: '#/components/schemas/Link'
                - description: 'Form endpoint that aids in updating this program


                    # Conditions


                    **Permission**: edit workspace'
              updateImmediately:
                allOf:
                - $ref: '#/components/schemas/Link'
                - description: 'Directly update this program


                    # Conditions


                    **Permission**: edit workspace'
              delete:
                allOf:
                - $ref: '#/components/schemas/Link'
                - description: 'Delete this program


                    # Conditions


                    **Permission**: admin'
              favor:
                allOf:
                - $ref: '#/components/schemas/Link'
                - description: 'Mark this program as favorited by the current user


                    # Conditions


                    Only present if the program is not yet favorited


                    Permission**: none but login is required'
              disfavor:
                allOf:
                - $ref: '#/components/schemas/Link'
                - description: 'Mark this program as not favorited by the current user


                    # Conditions

                    Only present if the program is favorited by the current user


                    Permission**: none but login is required'
              createWorkPackage:
                allOf:
                - $ref: '#/components/schemas/Link'
                - description: 'Form endpoint that aids in preparing and creating a work package


                    # Conditions


                    **Permission**: add work packages'
              createWorkPackageImmediately:
                allOf:
                - $ref: '#/components/schemas/Link'
                - description: 'Directly creates a work package in the program


                    # Conditions


                    **Permission**: add work packages'
              self:
                allOf:
                - $ref: '#/components/schemas/Link'
                - description: 'This program


                    **Resource**: Program'
              categories:
                allOf:
                - $ref: '#/components/schemas/Link'
                - description: 'Categories available in this program


                    **Resource**: Collection'
              types:
                allOf:
                - $ref: '#/components/schemas/Link'
                - description: 'Types available in this program


                    **Resource**: Collection


                    # Conditions


                    **Permission**: view work packages or manage types'
              versions:
                allOf:
                - $ref: '#/components/schemas/Link'
                - description: 'Versions available in this program


                    **Resource**: Collection


                    # Conditions


                    **Permission**: view work packages or manage versions'
              memberships:
                allOf:
                - $ref: '#/components/schemas/Link'
                - description: 'Memberships in the  program


                    **Resource**: Collection


                    # Conditions


                    **Permission**: view members'
              workPackages:
                allOf:
                - $ref: '#/components/schemas/Link'
                - description: 'Work Packages of this program


                    **Resource**: Collection'
              parent:
                allOf:
                - $ref: '#/components/schemas/Link'
                - description: 'Parent of the program


                    **Resource**: Program


                    # Conditions


                    **Permission** edit workspace'
              status:
                allOf:
                - $ref: '#/components/schemas/Link'
                - description: 'Denotes the status of the program, so whether the program is on track, at risk or is having trouble.


                    **Resource**: ProjectStatus


                    # Conditions


                    **Permission** edit workspace'
              storages:
                type: array
                items:
                  allOf:
                  - $ref: '#/components/schemas/Link'
                  - description: 'The link to a storage that is active for this program.


                      **Resource**: Storage


                      # Conditions


                      **Permission**: view_file_links'
              projectStorages:
                allOf:
                - $ref: '#/components/schemas/Link'
                - description: 'The project storage collection of this program.


                    **Resource**: Collection


                    # Conditions


                    **Permission**: view_file_links'
              ancestors:
                type: array
                items:
                  allOf:
                  - $ref: '#/components/schemas/Link'
                  - description: 'A collection of links to the ancestor workspace.


                      **Resource**: Workspace'
    CustomFieldProperties:
      type: object
      patternProperties:
        ^customField\d+$:
          type:
          - 'null'
          - number
          - boolean
          - string
          - object
          description: 'A custom field value, that belongs to a custom field of a simple type:


            - Boolean

            - Date

            - Float

            - Integer

            - Link (URL)

            - Text

            - Long text'
    ErrorResponse:
      type: object
      required:
      - _type
      - errorIdentifier
      - message
      properties:
        _embedded:
          type: object
          properties:
            details:
              type: object
              properties:
                attribute:
                  type: string
                  example: project
        _type:
          type: string
          enum:
          - Error
        errorIdentifier:
          type: string
          example: urn:openproject-org:api:v3:errors:PropertyConstraintViolation
        message:
          type: string
          example: Project can't be blank.
  responses:
    MissingContentType:
      description: Occurs when the client did not send a Content-Type header
      content:
        text/plain:
          schema:
            type: string
          example: Missing content-type header
    UnsupportedMediaType:
      description: Occurs when the client sends an unsupported Content-Type header.
      content:
        application/hal+json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            _type: Error
            errorIdentifier: urn:openproject-org:api:v3:errors:TypeNotSupported
            message: Expected CONTENT-TYPE to be (expected value) but got (actual value).
    InvalidRequestBody:
      description: Occurs when the client did not send a valid JSON object in the request body.
      content:
        application/hal+json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            _type: Error
            errorIdentifier: urn:openproject-org:api:v3:errors:InvalidRequestBody
            message: The request body was not a single JSON object.
  examples:
    ProgramBody:
      value:
        name: Program example
        statusExplanation:
          raw: Everything **fine**
        description:
          raw: Lorem **ipsum** dolor sit amet
        customField123: 123
        customComment123: Because it is 123!
        _links:
          parent:
            href: /api/v3/programs/123
          customField456:
            href: /api/v3/programs/315
    Program:
      value:
        _type: Program
        _links:
          self:
            href: /api/v3/programs/1
            title: Lorem
          createWorkPackage:
            href: /api/v3/programs/1/work_packages/form
            method: post
          createWorkPackageImmediate:
            href: /api/v3/programs/1/work_packages
            method: post
          categories:
            href: /api/v3/programs/1/categories
          types:
            href: /api/v3/programs/1/types
          versions:
            href: /api/v3/programs/1/versions
          workPackages:
            href: /api/v3/programs/1/work_packages
          memberships:
            href: /api/v3/memberships?filters=[{"project":{"operator":"=","values":["1"]}}]
          customField456:
            href: /api/v3/users/315
            title: A user
          parent:
            href: /api/v3/portfolio/123
            title: Parent portfolio
          ancestors:
          - href: /api/v3/portfolios/2
            title: Root portfolio
          - href: /api/v3/portfolios/12
            title: Grandparent portfolio
          - href: /api/v3/portfolios/123
            title: Parent portfolio
          status:
            href: /api/v3/project_statuses/on_track
            title: On track
        id: 1
        identifier: program_example
        name: Program example
        active: true
        public: false
        statusExplanation:
          format: markdown
          raw: Everything **fine**
          html: <p>Everything <strong>fine</strong></p>
        description:
          format: markdown
          raw: Lorem **ipsum** dolor sit amet
          html: <p>Lorem <strong>ipsum</strong> dolor sit amet</p>
        createdAt: '2014-05-21T08:51:20.396Z'
        updatedAt: '2014-05-21T08:51:20.396Z'
        customField123: 123
        customComment123: Why is the value 123?
    ProgramCollection:
      value:
        _type: Collection
        count: 2
        total: 2
        pageSize: 20
        offset: 1
        _embedded:
          elements:
          - _hint: Program resource shortened for brevity
            id: 1
            identifier: initialprogram
            name: DeathStar construction
            active: true
            public: true
          - _hint: Program resource shortened for brevity
            id: 2
            identifier: mysecret
            name: Palpatine's secret plan
            active: true
            public: false
        _links:
          self:
            href: /api/v3/programs?filters=%5B%5D&offset=1&pageSize=20
          jumpTo:
            href: /api/v3/programs?filters=%5B%5D&offset=%7Boffset%7D&pageSize=20
            templated: true
          changeSize:
            href: /api/v3/programs?filters=%5B%5D&offset=1&pageSize=%7Bsize%7D
            templated: true
          representations:
          - href: /programs.csv?filters=%5B%5D&offset=1&pageSize=20
            identifier: csv
            type: text/csv
            title: CSV
          - href: /programs.xls?filters=%5B%5D&offset=1&pageSize=20
            identifier: xls
            type: application/vnd.ms-excel
            title: XLS
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
