openapi: 3.2.0
info:
  description: You're looking at the current **stable** documentation of the OpenProject APIv3.
  title: OpenProject API V3 (Stable) Query Filter Instance Schema API
  version: '3'
servers:
- url: https://qa.openproject-edge.com
  description: Edge QA instance
- url: https://qa.openproject-stage.com
  description: Staging instance
- url: https://community.openproject.org
  description: Community instance
security:
- BasicAuth: []
tags:
- description: A QueryFilterInstanceSchema is a Schema specifically for describing QueryFilterInstances.
  name: Query Filter Instance Schema
paths:
  /api/v3/projects/{id}/queries/filter_instance_schemas:
    get:
      parameters:
      - description: Project id
        example: 1
        in: path
        name: id
        required: true
        schema:
          type: integer
      responses:
        '200':
          content:
            application/hal+json:
              examples:
                response:
                  value:
                    _embedded:
                      elements:
                      - _dependencies:
                        - _type: SchemaDependency
                          dependencies:
                            /api/v3/queries/operators/!:
                              values:
                                _links: {}
                                hasDefault: false
                                name: Values
                                required: true
                                type: '[]User'
                                writable: true
                            /api/v3/queries/operators/!*: {}
                            /api/v3/queries/operators/*: {}
                            /api/v3/queries/operators/=:
                              values:
                                _links: {}
                                hasDefault: false
                                name: Values
                                required: true
                                type: '[]User'
                                writable: true
                          'on': operator
                        _links:
                          filter:
                            href: /api/v3/queries/filters/assignee
                            title: Assignee
                          self:
                            href: /api/v3/queries/filter_instance_schemas/assignee
                        _type: QueryFilterInstanceSchema
                        filter:
                          _links: {}
                          hasDefault: false
                          name: Filter
                          required: true
                          type: QueryFilter
                          writable: true
                        name:
                          hasDefault: true
                          name: Name
                          required: true
                          type: String
                          writable: false
                      - _dependencies:
                        - _type: SchemaDependency
                          dependencies:
                            /api/v3/queries/operators/!:
                              values:
                                _links: {}
                                hasDefault: false
                                name: Values
                                required: true
                                type: '[]User'
                                writable: true
                            /api/v3/queries/operators/=:
                              values:
                                _links: {}
                                hasDefault: false
                                name: Values
                                required: true
                                type: '[]User'
                                writable: true
                          'on': operator
                        _links:
                          filter:
                            href: /api/v3/queries/filters/author
                            title: Author
                          self:
                            href: /api/v3/queries/filter_instance_schemas/author
                        _type: QueryFilterInstanceSchema
                        filter:
                          _links: {}
                          hasDefault: false
                          name: Filter
                          required: true
                          type: QueryFilter
                          writable: true
                        name:
                          hasDefault: true
                          name: Name
                          required: true
                          type: String
                          writable: false
                    _links:
                      self:
                        href: /api/v3/projects/42/queries/filter_instance_schemas
                    _type: Collection
                    count: 2
                    total: 2
              schema:
                $ref: '#/components/schemas/Query_Filter_Instance_Schemas_For_WorkspaceModel'
          description: OK
          headers: {}
        '403':
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                response:
                  value:
                    _type: Error
                    errorIdentifier: urn:openproject-org:api:v3:errors:Unauthenticated
                    message: You are not authorized to access this resource.
          description: 'Returned if the client does not have sufficient permissions to see it.


            **Required permission:** view work package in any project'
          headers: {}
      tags:
      - Query Filter Instance Schema
      description: 'Returns the list of QueryFilterInstanceSchemas defined for a query

        of the specified project.


        This endpoint is deprecated and replaced by `/api/v3/workspaces/{id}/queries/filter_instance_schemas`'
      operationId: List_Query_Filter_Instance_Schemas_for_Project
      summary: List Query Filter Instance Schemas for Project
  /api/v3/queries/filter_instance_schemas:
    get:
      responses:
        '200':
          content:
            application/hal+json:
              examples:
                response:
                  value:
                    _embedded:
                      elements:
                      - _dependencies:
                        - _type: SchemaDependency
                          dependencies:
                            /api/v3/queries/operators/!:
                              values:
                                _links: {}
                                hasDefault: false
                                name: Values
                                required: true
                                type: '[]User'
                                writable: true
                            /api/v3/queries/operators/!*: {}
                            /api/v3/queries/operators/*: {}
                            /api/v3/queries/operators/=:
                              values:
                                _links: {}
                                hasDefault: false
                                name: Values
                                required: true
                                type: '[]User'
                                writable: true
                          'on': operator
                        _links:
                          filter:
                            href: /api/v3/queries/filters/assignee
                            title: Assignee
                          self:
                            href: /api/v3/queries/filter_instance_schemas/assignee
                        _type: QueryFilterInstanceSchema
                        filter:
                          _links: {}
                          hasDefault: false
                          name: Filter
                          required: true
                          type: QueryFilter
                          writable: true
                        name:
                          hasDefault: true
                          name: Name
                          required: true
                          type: String
                          writable: false
                      - _dependencies:
                        - _type: SchemaDependency
                          dependencies:
                            /api/v3/queries/operators/!:
                              values:
                                _links: {}
                                hasDefault: false
                                name: Values
                                required: true
                                type: '[]User'
                                writable: true
                            /api/v3/queries/operators/=:
                              values:
                                _links: {}
                                hasDefault: false
                                name: Values
                                required: true
                                type: '[]User'
                                writable: true
                          'on': operator
                        _links:
                          filter:
                            href: /api/v3/queries/filters/author
                            title: Author
                          self:
                            href: /api/v3/queries/filter_instance_schemas/author
                        _type: QueryFilterInstanceSchema
                        filter:
                          _links: {}
                          hasDefault: false
                          name: Filter
                          required: true
                          type: QueryFilter
                          writable: true
                        name:
                          hasDefault: true
                          name: Name
                          required: true
                          type: String
                          writable: false
                    _links:
                      self:
                        href: /api/v3/queries/filter_instance_schemas
                    _type: Collection
                    count: 2
                    total: 2
              schema:
                $ref: '#/components/schemas/Query_Filter_Instance_SchemasModel'
          description: OK
          headers: {}
        '403':
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                response:
                  value:
                    _type: Error
                    errorIdentifier: urn:openproject-org:api:v3:errors:Unauthenticated
                    message: You are not authorized to access this resource.
          description: 'Returned if the client does not have sufficient permissions to see it.


            **Required permission:** view work package in any project'
          headers: {}
      tags:
      - Query Filter Instance Schema
      description: Returns the list of QueryFilterInstanceSchemas defined for a global query. That is a query not assigned to a project.
      operationId: List_Query_Filter_Instance_Schemas
      summary: List Query Filter Instance Schemas
  /api/v3/queries/filter_instance_schemas/{id}:
    get:
      parameters:
      - description: QueryFilterInstanceSchema identifier. The identifier is the filter identifier.
        example: author
        in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/hal+json:
              examples:
                response:
                  value:
                    _dependencies:
                    - _type: SchemaDependency
                      dependencies:
                        /api/v3/queries/operators/!:
                          values:
                            _links: {}
                            hasDefault: false
                            name: Values
                            required: true
                            type: '[]User'
                            writable: true
                        /api/v3/queries/operators/=:
                          values:
                            _links: {}
                            hasDefault: false
                            name: Values
                            required: true
                            type: '[]User'
                            writable: true
                      'on': operator
                    _links:
                      filter:
                        href: /api/v3/queries/filters/author
                        title: Author
                      self:
                        href: /api/v3/queries/filter_instance_schemas/author
                    _type: QueryFilterInstanceSchema
                    filter:
                      _links: {}
                      hasDefault: false
                      name: Filter
                      required: true
                      type: QueryFilter
                      writable: true
                    name:
                      hasDefault: true
                      name: Name
                      required: true
                      type: String
                      writable: false
              schema:
                $ref: '#/components/schemas/Query_Filter_Instance_SchemaModel'
          description: OK
          headers: {}
        '403':
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                response:
                  value:
                    _type: Error
                    errorIdentifier: urn:openproject-org:api:v3:errors:Unauthenticated
                    message: You are not authorized to access this resource.
          description: 'Returned if the client does not have sufficient permissions to see it.


            **Required permission:** view work package in any project'
          headers: {}
        '404':
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                response:
                  value:
                    _type: Error
                    errorIdentifier: urn:openproject-org:api:v3:errors:NotFound
                    message: The specified query does not exist.
          description: Returned if the QueryFilterInstanceSchema does not exist.
          headers: {}
      tags:
      - Query Filter Instance Schema
      description: Retrieve an individual QueryFilterInstanceSchema as identified by the id parameter.
      operationId: View_Query_Filter_Instance_Schema
      summary: View Query Filter Instance Schema
  /api/v3/workspace/{id}/queries/filter_instance_schemas:
    get:
      parameters:
      - description: Workspace id
        example: 1
        in: path
        name: id
        required: true
        schema:
          type: integer
      responses:
        '200':
          content:
            application/hal+json:
              examples:
                response:
                  value:
                    _embedded:
                      elements:
                      - _dependencies:
                        - _type: SchemaDependency
                          dependencies:
                            /api/v3/queries/operators/!:
                              values:
                                _links: {}
                                hasDefault: false
                                name: Values
                                required: true
                                type: '[]User'
                                writable: true
                            /api/v3/queries/operators/!*: {}
                            /api/v3/queries/operators/*: {}
                            /api/v3/queries/operators/=:
                              values:
                                _links: {}
                                hasDefault: false
                                name: Values
                                required: true
                                type: '[]User'
                                writable: true
                          'on': operator
                        _links:
                          filter:
                            href: /api/v3/queries/filters/assignee
                            title: Assignee
                          self:
                            href: /api/v3/queries/filter_instance_schemas/assignee
                        _type: QueryFilterInstanceSchema
                        filter:
                          _links: {}
                          hasDefault: false
                          name: Filter
                          required: true
                          type: QueryFilter
                          writable: true
                        name:
                          hasDefault: true
                          name: Name
                          required: true
                          type: String
                          writable: false
                      - _dependencies:
                        - _type: SchemaDependency
                          dependencies:
                            /api/v3/queries/operators/!:
                              values:
                                _links: {}
                                hasDefault: false
                                name: Values
                                required: true
                                type: '[]User'
                                writable: true
                            /api/v3/queries/operators/=:
                              values:
                                _links: {}
                                hasDefault: false
                                name: Values
                                required: true
                                type: '[]User'
                                writable: true
                          'on': operator
                        _links:
                          filter:
                            href: /api/v3/queries/filters/author
                            title: Author
                          self:
                            href: /api/v3/queries/filter_instance_schemas/author
                        _type: QueryFilterInstanceSchema
                        filter:
                          _links: {}
                          hasDefault: false
                          name: Filter
                          required: true
                          type: QueryFilter
                          writable: true
                        name:
                          hasDefault: true
                          name: Name
                          required: true
                          type: String
                          writable: false
                    _links:
                      self:
                        href: /api/v3/workspaces/42/queries/filter_instance_schemas
                    _type: Collection
                    count: 2
                    total: 2
              schema:
                $ref: '#/components/schemas/Query_Filter_Instance_Schemas_For_WorkspaceModel'
          description: OK
          headers: {}
        '403':
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                response:
                  value:
                    _type: Error
                    errorIdentifier: urn:openproject-org:api:v3:errors:Unauthenticated
                    message: You are not authorized to access this resource.
          description: 'Returned if the client does not have sufficient permissions to see it.


            **Required permission:** view work package in any workspace'
          headers: {}
      tags:
      - Query Filter Instance Schema
      description: Returns the list of QueryFilterInstanceSchemas defined for a query of the specified workspace.
      operationId: List_Query_Filter_Instance_Schemas_for_Workspace
      summary: List Query Filter Instance Schemas for Workspace
components:
  schemas:
    Link:
      type: object
      required:
      - href
      properties:
        href:
          type:
          - string
          - 'null'
          description: URL to the referenced resource (might be relative)
        title:
          type: string
          description: Representative label for the resource
        templated:
          type: boolean
          default: false
          description: If true the href contains parts that need to be replaced by the client
        method:
          type: string
          default: GET
          description: The HTTP verb to use when requesting the resource
        payload:
          type: object
          description: The payload to send in the request to achieve the desired result
        identifier:
          type: string
          description: An optional unique identifier to the link object
        type:
          type: string
          description: The MIME-Type of the returned resource.
      example:
        href: /api/v3/work_packages
        method: POST
    Query_Filter_Instance_SchemasModel:
      type: object
      example:
        _type: Collection
        total: 2
        count: 2
        _embedded:
          elements:
          - _type: QueryFilterInstanceSchema
            _dependencies:
            - _type: SchemaDependency
              'on': operator
              dependencies:
                /api/v3/queries/operators/=:
                  values:
                    type: '[]User'
                    name: Values
                    required: true
                    hasDefault: false
                    writable: true
                    _links: {}
                /api/v3/queries/operators/!:
                  values:
                    type: '[]User'
                    name: Values
                    required: true
                    hasDefault: false
                    writable: true
                    _links: {}
                /api/v3/queries/operators/!*: {}
                /api/v3/queries/operators/*: {}
            name:
              type: String
              name: Name
              required: true
              hasDefault: true
              writable: false
            filter:
              type: QueryFilter
              name: Filter
              required: true
              hasDefault: false
              writable: true
              _links: {}
            _links:
              self:
                href: /api/v3/queries/filter_instance_schemas/assignee
              filter:
                href: /api/v3/queries/filters/assignee
                title: Assignee
          - _type: QueryFilterInstanceSchema
            _dependencies:
            - _type: SchemaDependency
              'on': operator
              dependencies:
                /api/v3/queries/operators/=:
                  values:
                    type: '[]User'
                    name: Values
                    required: true
                    hasDefault: false
                    writable: true
                    _links: {}
                /api/v3/queries/operators/!:
                  values:
                    type: '[]User'
                    name: Values
                    required: true
                    hasDefault: false
                    writable: true
                    _links: {}
            name:
              type: String
              name: Name
              required: true
              hasDefault: true
              writable: false
            filter:
              type: QueryFilter
              name: Filter
              required: true
              hasDefault: false
              writable: true
              _links: {}
            _links:
              self:
                href: /api/v3/queries/filter_instance_schemas/author
              filter:
                href: /api/v3/queries/filters/author
                title: Author
        _links:
          self:
            href: /api/v3/queries/filter_instance_schemas
    Query_Filter_Instance_SchemaModel:
      type: object
      required:
      - name
      - _links
      properties:
        name:
          type: string
          description: Describes the name attribute
          readOnly: true
        _links:
          type: object
          required:
          - self
          - filter
          properties:
            self:
              allOf:
              - $ref: '#/components/schemas/Link'
              - description: 'This QueryFilterInstanceSchema (same as for schema)


                  **Resource**: QueryFilterInstanceSchema'
                readOnly: true
            filter:
              allOf:
              - $ref: '#/components/schemas/Link'
              - description: 'The filter for which this schema is specific


                  **Resource**: Filter'
                readOnly: true
      example:
        _type: QueryFilterInstanceSchema
        _dependencies:
        - _type: SchemaDependency
          'on': operator
          dependencies:
            /api/v3/queries/operators/=:
              values:
                type: '[]User'
                name: Values
                required: true
                hasDefault: false
                writable: true
                _links: {}
            /api/v3/queries/operators/!:
              values:
                type: '[]User'
                name: Values
                required: true
                hasDefault: false
                writable: true
                _links: {}
        name: A name
        _links:
          self:
            href: /api/v3/queries/filter_instance_schemas/author
          filter:
            href: /api/v3/queries/filters/author
            title: Author
    Query_Filter_Instance_Schemas_For_WorkspaceModel:
      type: object
      example:
        _type: Collection
        total: 2
        count: 2
        _embedded:
          elements:
          - _type: QueryFilterInstanceSchema
            _dependencies:
            - _type: SchemaDependency
              'on': operator
              dependencies:
                /api/v3/queries/operators/=:
                  values:
                    type: '[]User'
                    name: Values
                    required: true
                    hasDefault: false
                    writable: true
                    _links: {}
                /api/v3/queries/operators/!:
                  values:
                    type: '[]User'
                    name: Values
                    required: true
                    hasDefault: false
                    writable: true
                    _links: {}
                /api/v3/queries/operators/!*: {}
                /api/v3/queries/operators/*: {}
            name:
              type: String
              name: Name
              required: true
              hasDefault: true
              writable: false
            filter:
              type: QueryFilter
              name: Filter
              required: true
              hasDefault: false
              writable: true
              _links: {}
            _links:
              self:
                href: /api/v3/queries/filter_instance_schemas/assignee
              filter:
                href: /api/v3/queries/filters/assignee
                title: Assignee
          - _type: QueryFilterInstanceSchema
            _dependencies:
            - _type: SchemaDependency
              'on': operator
              dependencies:
                /api/v3/queries/operators/=:
                  values:
                    type: '[]User'
                    name: Values
                    required: true
                    hasDefault: false
                    writable: true
                    _links: {}
                /api/v3/queries/operators/!:
                  values:
                    type: '[]User'
                    name: Values
                    required: true
                    hasDefault: false
                    writable: true
                    _links: {}
            name:
              type: String
              name: Name
              required: true
              hasDefault: true
              writable: false
            filter:
              type: QueryFilter
              name: Filter
              required: true
              hasDefault: false
              writable: true
              _links: {}
            _links:
              self:
                href: /api/v3/queries/filter_instance_schemas/author
              filter:
                href: /api/v3/queries/filters/author
                title: Author
        _links:
          self:
            href: /api/v3/workspaces/42/queries/filter_instance_schemas
    ErrorResponse:
      type: object
      required:
      - _type
      - errorIdentifier
      - message
      properties:
        _embedded:
          type: object
          properties:
            details:
              type: object
              properties:
                attribute:
                  type: string
                  example: project
        _type:
          type: string
          enum:
          - Error
        errorIdentifier:
          type: string
          example: urn:openproject-org:api:v3:errors:PropertyConstraintViolation
        message:
          type: string
          example: Project can't be blank.
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
